FROM nginx:alpine

LABEL org.opencontainers.image.source="https://github.com/bibhutibbb/cloud-trader-pro-build"

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy static HTML, JS, CSS, and image files to Nginx html directory
COPY server/static /usr/share/nginx/html
